import { Canvas } from '@react-three/fiber'
import { CustomPlayer } from '@/components/CharacterCreator'
import { OrbitControls } from '@react-three/drei'
import { Suspense } from 'react'

// 3D scene entry point for the character creator route.
// Renders the Fiber canvas with our avatar controls.


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function NESModel(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/cartridge_nes.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
        scale={3}
        rotation={[10, 3, 20]}
        position={[0, 0, 4]}
          name="cartridge_nes"
          castShadow
          receiveShadow
          geometry={nodes.cartridge_nes.geometry}
          material-color={'red'}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/cartridge_nes.glb')


export default function Page () {
  return (
    <Canvas style={{ height: '100%', width: '100%' }}>
        <OrbitControls/>
      {/* Suspense handles lazy-loaded GLTF assets and Drei helpers */}
      <Suspense fallback={null}>
      <NESModel/>
      </Suspense>
    </Canvas>
  )
}
