import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function MapModel(props) {
  const { nodes, materials } = useGLTF("http://127.0.0.1:5500/starting_map.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[132.16, 1.06, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053.geometry}
          material={materials["Material.113"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_2.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_3.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_4.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_5.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_6.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_7.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_8.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_9.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_10.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_11.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_12.geometry}
          material={materials["Material.017"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_13.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_14.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_15.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_16.geometry}
          material={materials["Material.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_17.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_18.geometry}
          material={materials["Material.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_19.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_20.geometry}
          material={materials["Material.027"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_21.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_22.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_23.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_24.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_25.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_26.geometry}
          material={materials["Material.033"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_27.geometry}
          material={materials["Material.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_28.geometry}
          material={materials["Material.035"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_29.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_30.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_31.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_32.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_33.geometry}
          material={materials["Material.040"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_34.geometry}
          material={materials["Material.041"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_35.geometry}
          material={materials["Material.042"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_36.geometry}
          material={materials["Material.043"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_37.geometry}
          material={materials["Material.044"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_38.geometry}
          material={materials["Material.045"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_39.geometry}
          material={materials["Material.046"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_40.geometry}
          material={materials["Material.047"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_41.geometry}
          material={materials["Material.048"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_42.geometry}
          material={materials["Material.049"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_43.geometry}
          material={materials["Material.050"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_44.geometry}
          material={materials["Material.051"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_45.geometry}
          material={materials["Material.052"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_46.geometry}
          material={materials["Material.053"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_47.geometry}
          material={materials["Material.054"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_48.geometry}
          material={materials["Material.055"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_49.geometry}
          material={materials["Material.056"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_50.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_51.geometry}
          material={materials["Material.058"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_52.geometry}
          material={materials["Material.059"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_53.geometry}
          material={materials["Material.060"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_54.geometry}
          material={materials["Material.061"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_55.geometry}
          material={materials["Material.062"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_56.geometry}
          material={materials["Material.063"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_57.geometry}
          material={materials["Material.064"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_58.geometry}
          material={materials["Material.065"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_59.geometry}
          material={materials["Material.066"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_60.geometry}
          material={materials["Material.067"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_61.geometry}
          material={materials["Material.068"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_62.geometry}
          material={materials["Material.069"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_63.geometry}
          material={materials["Material.070"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_64.geometry}
          material={materials["Material.071"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_65.geometry}
          material={materials["Material.072"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_66.geometry}
          material={materials["Material.073"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_67.geometry}
          material={materials["Material.074"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_68.geometry}
          material={materials["Material.075"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_69.geometry}
          material={materials["Material.076"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_70.geometry}
          material={materials["Material.077"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_71.geometry}
          material={materials["Material.078"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_72.geometry}
          material={materials["Material.079"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_73.geometry}
          material={materials["Material.080"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_74.geometry}
          material={materials["Material.081"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_75.geometry}
          material={materials["Material.082"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_76.geometry}
          material={materials["Material.083"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_77.geometry}
          material={materials["Material.084"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_78.geometry}
          material={materials["Material.085"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_79.geometry}
          material={materials["Material.086"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_80.geometry}
          material={materials["Material.087"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_81.geometry}
          material={materials["Material.088"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_82.geometry}
          material={materials["Material.089"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_83.geometry}
          material={materials["Material.090"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_84.geometry}
          material={materials["Material.091"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_85.geometry}
          material={materials["Material.092"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_86.geometry}
          material={materials["Material.093"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_87.geometry}
          material={materials["Material.094"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_88.geometry}
          material={materials["Material.095"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_89.geometry}
          material={materials["Material.096"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_90.geometry}
          material={materials["Material.097"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_91.geometry}
          material={materials["Material.098"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_92.geometry}
          material={materials["Material.099"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_93.geometry}
          material={materials["Material.100"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_94.geometry}
          material={materials["Material.101"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_95.geometry}
          material={materials["Material.102"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_96.geometry}
          material={materials["Material.103"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_97.geometry}
          material={materials["Material.104"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_98.geometry}
          material={materials["Material.105"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_99.geometry}
          material={materials["Material.106"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_100.geometry}
          material={materials["Material.107"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_101.geometry}
          material={materials["Material.108"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_102.geometry}
          material={materials["Material.109"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_103.geometry}
          material={materials["Material.110"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_104.geometry}
          material={materials["Material.111"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_105.geometry}
          material={materials["Material.112"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_106.geometry}
          material={materials["Material.114"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_107.geometry}
          material={materials["Material.115"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_108.geometry}
          material={materials["Material.116"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_109.geometry}
          material={materials["Material.117"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_110.geometry}
          material={materials["Material.118"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_111.geometry}
          material={materials["Material.119"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_112.geometry}
          material={materials["Material.120"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_113.geometry}
          material={materials["Material.121"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_114.geometry}
          material={materials["Material.122"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_115.geometry}
          material={materials["Material.123"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_116.geometry}
          material={materials["Material.124"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_117.geometry}
          material={materials["Material.125"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_118.geometry}
          material={materials["Material.126"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_119.geometry}
          material={materials["Material.127"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_120.geometry}
          material={materials["Material.128"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_121.geometry}
          material={materials["Material.129"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_122.geometry}
          material={materials["Material.130"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_123.geometry}
          material={materials["Material.131"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_124.geometry}
          material={materials["Material.132"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_125.geometry}
          material={materials["Material.133"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_126.geometry}
          material={materials["Material.134"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_127.geometry}
          material={materials["Material.135"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_128.geometry}
          material={materials["Material.136"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_129.geometry}
          material={materials["Material.137"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_130.geometry}
          material={materials["Material.138"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_131.geometry}
          material={materials["Material.139"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_132.geometry}
          material={materials["Material.140"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_133.geometry}
          material={materials["Material.141"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_134.geometry}
          material={materials["Material.142"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_135.geometry}
          material={materials["Material.143"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_136.geometry}
          material={materials["Material.144"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_137.geometry}
          material={materials["Material.145"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_138.geometry}
          material={materials["Material.146"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_139.geometry}
          material={materials["Material.147"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_140.geometry}
          material={materials["Material.148"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_141.geometry}
          material={materials["Material.149"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_142.geometry}
          material={materials["Material.150"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_143.geometry}
          material={materials["Material.151"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_144.geometry}
          material={materials["Material.152"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_145.geometry}
          material={materials["Material.153"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_146.geometry}
          material={materials["Material.154"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_147.geometry}
          material={materials["Material.155"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_148.geometry}
          material={materials["Material.156"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_149.geometry}
          material={materials["Material.157"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_150.geometry}
          material={materials["Material.158"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_151.geometry}
          material={materials["Material.159"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_152.geometry}
          material={materials["Material.160"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_153.geometry}
          material={materials["Material.161"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_154.geometry}
          material={materials["Material.358"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_155.geometry}
          material={materials["Material.162"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_156.geometry}
          material={materials["Material.163"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_157.geometry}
          material={materials["Material.164"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_158.geometry}
          material={materials["Material.165"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_159.geometry}
          material={materials["Material.166"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_160.geometry}
          material={materials["Material.167"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_161.geometry}
          material={materials["Material.168"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_162.geometry}
          material={materials["Material.169"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_163.geometry}
          material={materials["Material.170"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_164.geometry}
          material={materials["Material.171"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_165.geometry}
          material={materials["Material.172"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_166.geometry}
          material={materials["Material.173"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_167.geometry}
          material={materials["Material.174"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_168.geometry}
          material={materials["Material.175"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_169.geometry}
          material={materials["Material.176"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_170.geometry}
          material={materials["Material.177"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_171.geometry}
          material={materials["Material.178"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_172.geometry}
          material={materials["Material.179"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_173.geometry}
          material={materials["Material.180"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_174.geometry}
          material={materials["Material.181"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_175.geometry}
          material={materials["Material.182"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_176.geometry}
          material={materials["Material.183"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_177.geometry}
          material={materials["Material.184"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_178.geometry}
          material={materials["Material.185"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_179.geometry}
          material={materials["Material.186"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_180.geometry}
          material={materials["Material.187"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_181.geometry}
          material={materials["Material.188"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_182.geometry}
          material={materials["Material.189"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_183.geometry}
          material={materials["Material.190"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_184.geometry}
          material={materials["Material.191"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_185.geometry}
          material={materials["Material.192"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_186.geometry}
          material={materials["Material.193"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_187.geometry}
          material={materials["Material.194"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_188.geometry}
          material={materials["Material.195"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_189.geometry}
          material={materials["Material.196"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_190.geometry}
          material={materials["Material.197"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_191.geometry}
          material={materials["Material.198"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_192.geometry}
          material={materials["Material.199"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_193.geometry}
          material={materials["Material.200"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_194.geometry}
          material={materials["Material.201"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_195.geometry}
          material={materials["Material.202"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_196.geometry}
          material={materials["Material.203"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_197.geometry}
          material={materials["Material.204"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_198.geometry}
          material={materials["Material.205"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_199.geometry}
          material={materials["Material.206"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_200.geometry}
          material={materials["Material.207"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_201.geometry}
          material={materials["Material.208"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_202.geometry}
          material={materials["Material.209"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_203.geometry}
          material={materials["Material.210"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_204.geometry}
          material={materials["Material.211"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_205.geometry}
          material={materials["Material.214"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_206.geometry}
          material={materials["Material.215"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_207.geometry}
          material={materials["Material.216"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_208.geometry}
          material={materials["Material.217"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_209.geometry}
          material={materials["Material.218"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_210.geometry}
          material={materials["Material.219"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_211.geometry}
          material={materials["Material.220"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_212.geometry}
          material={materials["Material.221"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_213.geometry}
          material={materials["Material.222"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_214.geometry}
          material={materials["Material.223"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_215.geometry}
          material={materials["Material.224"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_216.geometry}
          material={materials["Material.225"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_217.geometry}
          material={materials["Material.226"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_218.geometry}
          material={materials["Material.227"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_219.geometry}
          material={materials["Material.228"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_220.geometry}
          material={materials["Material.229"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_221.geometry}
          material={materials["Material.230"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_222.geometry}
          material={materials["Material.231"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_223.geometry}
          material={materials["Material.232"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_224.geometry}
          material={materials["Material.233"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_225.geometry}
          material={materials["Material.234"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_226.geometry}
          material={materials["Material.235"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_227.geometry}
          material={materials["Material.236"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_228.geometry}
          material={materials["Material.237"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_229.geometry}
          material={materials["Material.238"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_230.geometry}
          material={materials["Material.239"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_231.geometry}
          material={materials["Material.240"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_232.geometry}
          material={materials["Material.241"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_233.geometry}
          material={materials["Material.242"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_234.geometry}
          material={materials["Material.243"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_235.geometry}
          material={materials["Material.244"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_236.geometry}
          material={materials["Material.245"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_237.geometry}
          material={materials["Material.246"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_238.geometry}
          material={materials["Material.247"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_239.geometry}
          material={materials["Material.248"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_240.geometry}
          material={materials["Material.249"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_241.geometry}
          material={materials["Material.250"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_242.geometry}
          material={materials["Material.251"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_243.geometry}
          material={materials["Material.252"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_244.geometry}
          material={materials["Material.253"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_245.geometry}
          material={materials["Material.254"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_246.geometry}
          material={materials["Material.255"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_247.geometry}
          material={materials["Material.256"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_248.geometry}
          material={materials["Material.257"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_249.geometry}
          material={materials["Material.258"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_250.geometry}
          material={materials["Material.259"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_251.geometry}
          material={materials["Material.260"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_252.geometry}
          material={materials["Material.261"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_253.geometry}
          material={materials["Material.262"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_254.geometry}
          material={materials["Material.263"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_255.geometry}
          material={materials["Material.264"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_256.geometry}
          material={materials["Material.265"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_257.geometry}
          material={materials["Material.266"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_258.geometry}
          material={materials["Material.267"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_259.geometry}
          material={materials["Material.268"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_260.geometry}
          material={materials["Material.269"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_261.geometry}
          material={materials["Material.270"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_262.geometry}
          material={materials["Material.271"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_263.geometry}
          material={materials["Material.272"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_264.geometry}
          material={materials["Material.273"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_265.geometry}
          material={materials["Material.274"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_266.geometry}
          material={materials["Material.275"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_267.geometry}
          material={materials["Material.276"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_268.geometry}
          material={materials["Material.278"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_269.geometry}
          material={materials["Material.279"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_270.geometry}
          material={materials["Material.280"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_271.geometry}
          material={materials["Material.281"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_272.geometry}
          material={materials["Material.282"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_273.geometry}
          material={materials["Material.283"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_274.geometry}
          material={materials["Material.284"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_275.geometry}
          material={materials["Material.285"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_276.geometry}
          material={materials["Material.286"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_277.geometry}
          material={materials["Material.287"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_278.geometry}
          material={materials["Material.288"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_279.geometry}
          material={materials["Material.289"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_280.geometry}
          material={materials["Material.290"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_281.geometry}
          material={materials["Material.291"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_282.geometry}
          material={materials["Material.292"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_283.geometry}
          material={materials["Material.293"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_284.geometry}
          material={materials["Material.295"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_285.geometry}
          material={materials["Material.296"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_286.geometry}
          material={materials["Material.297"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_287.geometry}
          material={materials["Material.298"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_288.geometry}
          material={materials["Material.299"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_289.geometry}
          material={materials["Material.300"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_290.geometry}
          material={materials["Material.301"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_291.geometry}
          material={materials["Material.302"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_292.geometry}
          material={materials["Material.303"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_293.geometry}
          material={materials["Material.304"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_294.geometry}
          material={materials["Material.305"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_295.geometry}
          material={materials["Material.306"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_296.geometry}
          material={materials["Material.307"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_297.geometry}
          material={materials["Material.308"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_298.geometry}
          material={materials["Material.309"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_299.geometry}
          material={materials["Material.310"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_300.geometry}
          material={materials["Material.311"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_301.geometry}
          material={materials["Material.312"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_302.geometry}
          material={materials["Material.313"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_303.geometry}
          material={materials["Material.314"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_304.geometry}
          material={materials["Material.315"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_305.geometry}
          material={materials["Material.316"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_306.geometry}
          material={materials["Material.317"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_307.geometry}
          material={materials["Material.318"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_308.geometry}
          material={materials["Material.319"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_309.geometry}
          material={materials["Material.320"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_310.geometry}
          material={materials["Material.321"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_311.geometry}
          material={materials["Material.322"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_312.geometry}
          material={materials["Material.323"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_313.geometry}
          material={materials["Material.324"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_314.geometry}
          material={materials["Material.325"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_315.geometry}
          material={materials["Material.326"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_316.geometry}
          material={materials["Material.327"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_317.geometry}
          material={materials["Material.328"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_318.geometry}
          material={materials["Material.329"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_319.geometry}
          material={materials["Material.330"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_320.geometry}
          material={materials["Material.331"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_321.geometry}
          material={materials["Material.332"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_322.geometry}
          material={materials["Material.333"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_323.geometry}
          material={materials["Material.334"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_324.geometry}
          material={materials["Material.335"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_325.geometry}
          material={materials["Material.336"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_326.geometry}
          material={materials["Material.337"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_327.geometry}
          material={materials["Material.338"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_328.geometry}
          material={materials["Material.339"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_329.geometry}
          material={materials["Material.340"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_330.geometry}
          material={materials["Material.341"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_331.geometry}
          material={materials["Material.342"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_332.geometry}
          material={materials["Material.343"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_333.geometry}
          material={materials["Material.344"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_334.geometry}
          material={materials["Material.345"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_335.geometry}
          material={materials["Material.346"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_336.geometry}
          material={materials["Material.347"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_337.geometry}
          material={materials["Material.351"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_338.geometry}
          material={materials["Material.353"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_339.geometry}
          material={materials["Material.354"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_340.geometry}
          material={materials["Material.356"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_341.geometry}
          material={materials["Material.357"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_342.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_343.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_344.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube053_345.geometry}
          material={materials["Material.007"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("http://127.0.0.1:5500/starting_map.glb");